import random

def lotto(): # function takes a list of 6 numbers from user and check how many of them is the same as in the list generated by computer
    generated_numbers = []
    guessed_numbers = []
    
    for i in range(6):
        number = (input("Guess the number: "))      
        try:
            number = int(number)        
        except ValueError:
            print("It's not a number!") 
            return lotto()      
        if 1 <= number <= 49 and number not in guessed_numbers:
            guessed_numbers.append(number)
        elif number > 49:
            print("Number is out of range 0-49")
            return lotto()
        elif number in guessed_numbers:
            print("You already entered this number!")
            return lotto()

    guessed_numbers.sort()
    print(guessed_numbers)

    for i in range(6):
        random_number = random.randint(1, 49)
        if random_number in generated_numbers:
            random_number = random_number + 1
            generated_numbers.append(random_number)
        else:
            generated_numbers.append(random_number)
 
    generated_numbers.sort()
    print(generated_numbers)

    result = len(list(set(guessed_numbers).intersection(generated_numbers)))

    return result

print(lotto())
