import random
random_number = random.randint(0,100) 

def guess(): # function takes number from user and compares it with the one generated by computer
    global random_number 
    user_number = input('Guess the number: ')  
    try:
        user_number = int(user_number) 
    except ValueError:
        print("It's not a number!") 
        return guess() 
    if user_number < random_number: 
        print("To small!") 
        return guess() 
    elif user_number > random_number:
        print("To big!") 
        return guess() 
    else:
        return "You win!" 

print(guess())
